# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any
import ctypes
import os
import socket
import subprocess
import sys
import time

def _read_cfg(path: Any) -> Any:
    ...

def _tcp_alive(host: Any, port: Any, timeout: Any) -> Any:
    ...

def _run(cmd: Any, timeout: Any) -> Any:
    ...

def _acquire_lock(lock_path: Any) -> Any:
    ...

def main() -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import subprocess
import time
import os
import socket
import ctypes
import sys
import msvcrt
import ntpath